apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shadi-hub-xyz-tls
spec:
  secretName: shadi-hub-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shadihub.xyz
  dnsNames:
    - shadihub.xyz
    - www.shadihub.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shadihub.xyz
          - www.shadihub.xyz
